python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.1 --K 1
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.1 --K 2
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.1 --K 3
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.1 --K 5
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.1 --K 8
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.1 --K 12
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.1 --K 16
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.1 --K 24
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.1 --K 32
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.1 --K 48

python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.3 --K 1
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.3 --K 2
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.3 --K 3
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.3 --K 5
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.3 --K 8
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.3 --K 12
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.3 --K 16
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.3 --K 24
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.3 --K 32
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.3 --K 48

python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.5 --K 1
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.5 --K 2
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.5 --K 3
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.5 --K 5
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.5 --K 8
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.5 --K 12
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.5 --K 16
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.5 --K 24
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.5 --K 32
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.5 --K 48

python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.7 --K 1
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.7 --K 2
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.7 --K 3
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.7 --K 5
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.7 --K 8
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.7 --K 12
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.7 --K 16
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.7 --K 24
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.7 --K 32
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.7 --K 48

python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.9 --K 1
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.9 --K 2
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.9 --K 3
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.9 --K 5
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.9 --K 8
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.9 --K 12
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.9 --K 16
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.9 --K 24
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.9 --K 32
python main.py --method ours --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale --alpha 0.9 --K 48