python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 1 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 2 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 3 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 5 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 6 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 7 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 8 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 9 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 11 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 13 --device 1 --process detect --use_prop --scale 

python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 14 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 15 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 16 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 18 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 20 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 22 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 24 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 26 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 28 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 30 --device 1 --process detect --use_prop --scale 

python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 32 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 33 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 35 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 36 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 38 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 39 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 40 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 41 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 42 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 45 --device 1 --process detect --use_prop --scale 

python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 46 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 48 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 50 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 51 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 52 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 53 --device 1 --process detect --use_prop --scale 
python main.py --method ours --backbone mixhop --dataset roman-empire --ood_type label --mode detect --use_bn --nc_dim 54 --device 1 --process detect --use_prop --scale 